version: '3.1'

services:

  db:
    image: postgres:14.0
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pgmypgpasswordxD
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgrespersist:/var/lib/postgresql/data

volumes:
  postgrespersist:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/dathin/Documents/postgrespersist
